# Generated by Django 5.1.3 on 2024-11-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='contact_number',
            field=models.CharField(max_length=50),
        ),
    ]
