# Generated by Django 4.2.6 on 2024-11-27 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_manager', '0003_dietaryrestrictions_menu_manage_item_id_96ddd5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinglogs',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_manager.menu'),
        ),
    ]
