# Generated by Django 4.2.6 on 2024-11-27 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_manager', '0004_alter_processinglogs_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinglogs',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu_manager.menu'),
            preserve_default=False,
        ),
    ]
